### ISSUE TITLE
Missing Plugin Exception

### ISSUE THREAD

**Issue by deveshgarg-max** [myamolane/docusign-sdk#2]
![Screenshot (187)](https://user-images.githubusercontent.com/53038326/99339135-9b013b80-28ab-11eb-9825-3b90f66b09b5.png)

**Comment by myamolane** [comment]
Android or iOS ? I just tested with iOS, can't reproduce this issue.

**Comment by deveshgarg-max** [comment]
Hey @myamolane it is on Android

**Comment by deveshgarg-max** [comment]
How do we use DocuSign API any suggestions?

**Comment by myamolane** [comment]
Currently, this plugin still only support iOS. Maybe will support Android in 2 weeks.

**Comment by myamolane** [comment]
You should always login before use any other api. And i recommend the offline sign in mode, since offline mode has much better user experience than online mode. 
[Offline Mode](https://github.com/myamolane/docusign-sdk#offline-mode)
